apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: odis
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: odis
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
